var express = require('express'); //can change var to const bc won't change... generated by express
var router = express.Router();
const request = require('request');

/* GET home page. */
router.get('/', function(req, res, next) {
  const url = "http://api.giphy.com/v1/gifs/random?api_key=bQAqfT0bpnNUFNJDaXSFRcPEmLgWpOzq";
  request.get(url, (err, response, body) => {
     if(err) { console.error(err) }

    body = JSON.parse(body);
    console.log(body);

    const imgUrl = body.data.image_url

    res.render('index', { title: 'Make School Giphy', imgUrl: imgUrl });
  })
});

router.get('/search', (req, res, next) => {
  res.render('search');
})

router.post('/search', (req, res, next) => {
  const query = req.body['giphy-query']
  const url= `http://api.giphy.com/v1/gifs/search?api_key=bQAqfT0bpnNUFNJDaXSFRcPEmLgWpOzq&q=${query}`;

  request.get(url, (err, response, body) => {
      if(err) { console.error(err) }

      body = JSON.parse(body);

      const randomResult = body.data[Math.floor(Math.random() * body.data.length)];
      const searchResultUrl = randomResult.images.fixed_height.url;

      res.render('search', { searchResultUrl: searchResultUrl });
  })
});

module.exports = router;
